//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperScript.ExternalFile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class List {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal List() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperScript.ExternalFile.Resources.List", typeof(List).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you wish to empty the store of all current assets.\n\nThis may cause problems for users of the website..
        /// </summary>
        public static string ConfirmEmpty {
            get {
                return ResourceManager.GetString("ConfirmEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you wish to initialise the store. If the store currently has assets then these will be deleted.\n\nThis may cause problems for users of the website..
        /// </summary>
        public static string ConfirmInit {
            get {
                return ResourceManager.GetString("ConfirmInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you wish to re-initialise the store. If the store currently has assets then these will be deleted.\n\nThis may cause problems for users of the website.\n\n[Re-initialising the store is equivalent to removing and then initialising the store.].
        /// </summary>
        public static string ConfirmReinit {
            get {
                return ResourceManager.GetString("ConfirmReinit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that you wish to remove the store.\n\nThis may cause problems for users of the website..
        /// </summary>
        public static string ConfirmRemove {
            get {
                return ResourceManager.GetString("ConfirmRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client cache period.
        /// </summary>
        public static string HeaderClientCachePeriod {
            get {
                return ResourceManager.GetString("HeaderClientCachePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content length.
        /// </summary>
        public static string HeaderContentLength {
            get {
                return ResourceManager.GetString("HeaderContentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content type.
        /// </summary>
        public static string HeaderContentType {
            get {
                return ResourceManager.GetString("HeaderContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string HeaderKey {
            get {
                return ResourceManager.GetString("HeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longevity.
        /// </summary>
        public static string HeaderLongevity {
            get {
                return ResourceManager.GetString("HeaderLongevity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string InstructionDelete {
            get {
                return ResourceManager.GetString("InstructionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string InstructionEmpty {
            get {
                return ResourceManager.GetString("InstructionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialise.
        /// </summary>
        public static string InstructionInit {
            get {
                return ResourceManager.GetString("InstructionInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-initiaise.
        /// </summary>
        public static string InstructionReInit {
            get {
                return ResourceManager.GetString("InstructionReInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string InstructionReload {
            get {
                return ResourceManager.GetString("InstructionReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string InstructionRemove {
            get {
                return ResourceManager.GetString("InstructionRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string InstructionView {
            get {
                return ResourceManager.GetString("InstructionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been emptied..
        /// </summary>
        public static string MsgEmpty {
            get {
                return ResourceManager.GetString("MsgEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been initialised..
        /// </summary>
        public static string MsgInit {
            get {
                return ResourceManager.GetString("MsgInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been re-initialised..
        /// </summary>
        public static string MsgReInit {
            get {
                return ResourceManager.GetString("MsgReInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store has been removed..
        /// </summary>
        public static string MsgRemove {
            get {
                return ResourceManager.GetString("MsgRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperScript.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page lists all the assets currently contained in the store, along with some commands to manipulate the store..
        /// </summary>
        public static string PageHeader {
            get {
                return ResourceManager.GetString("PageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Assets.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens in a new tab/window.
        /// </summary>
        public static string TooltipView {
            get {
                return ResourceManager.GetString("TooltipView", resourceCulture);
            }
        }
    }
}
